import { createHash } from "node:crypto";
import { lstat, readdir, readFile } from "node:fs/promises";
import { homedir } from "node:os";
import { join, relative } from "node:path";
import type { AgentId, Audit, Config, Item, Protection, StorageClass } from "./model.js";
const rootsFor = (agent: AgentId): string[] => agent === "claude" ? [join(homedir(), ".claude", "projects"), join(homedir(), ".claude", "debug"), join(homedir(), ".claude", "file-history"), join(homedir(), ".claude", "todos")] : [join(homedir(), ".codex", "sessions"), join(homedir(), ".codex", "logs"), join(homedir(), ".codex", "tmp")];
const classFor = (root: string, file: string): StorageClass => { const value = `${root}/${file}`.toLowerCase(); if (/credential|auth|secret|token|\.npmrc|\.env/.test(value)) return "credential"; if (/settings|config|\.json$/.test(value) && /\.codex|\.claude/.test(value) && !/project|session/.test(value)) return "configuration"; if (/debug|log/.test(value)) return "debug"; if (/file-history|snapshot/.test(value)) return "file-history"; if (/tmp|temp|output/.test(value)) return "temp"; if (/session|transcript|conversation|todo/.test(value)) return "session"; return "unknown"; };
async function walk(root: string, dir = root, out: Array<{ path: string; relative: string; stat: Awaited<ReturnType<typeof lstat>> }> = []): Promise<typeof out> { let entries; try { entries = await readdir(dir, { withFileTypes: true }); } catch { return out; } for (const entry of entries) { if ([".git", "node_modules"].includes(entry.name)) continue; const full = join(dir, entry.name); if (entry.isSymbolicLink()) { try { out.push({ path: full, relative: relative(root, full), stat: await lstat(full) }); } catch { /* skip vanished entries */ } continue; } if (entry.isDirectory()) await walk(root, full, out); else { try { out.push({ path: full, relative: relative(root, full), stat: await lstat(full) }); } catch { /* skip vanished entries */ } } } return out; }
function protection(itemClass: StorageClass, ageDays: number, config: Config, path: string, safetyDays: number): Protection { if (["configuration", "credential", "unknown"].includes(itemClass)) return "forbidden"; if (config.pins.some((pin) => path.includes(pin))) return "pinned"; if (ageDays < safetyDays) return "recent"; return "candidate"; }
export async function audit(config: Config = { pins: [] }, safetyDays = 2, agents: AgentId[] = ["claude", "codex"]): Promise<Audit> { const items: Item[] = []; const roots = agents.flatMap(rootsFor); for (const root of roots) for (const entry of await walk(root)) { const size = Number(entry.stat.size); const mtimeMs = Number(entry.stat.mtimeMs); const ageDays = Math.max(0, (Date.now() - mtimeMs) / 86_400_000); const cls = classFor(root, entry.relative); const symlink = entry.stat.isSymbolicLink(); const protect = symlink ? "symlink" : protection(cls, ageDays, config, entry.path, safetyDays); items.push({ id: createHash("sha256").update(`${entry.path}\0${size}\0${mtimeMs}`).digest("hex").slice(0, 16), agent: root.includes(".codex") ? "codex" : "claude", path: entry.path, relative: entry.relative.replaceAll("\\", "/"), class: cls, bytes: size, mtime: entry.stat.mtime.toISOString(), ageDays, protection: protect, reason: protect === "candidate" ? `older than ${safetyDays} days` : protect === "forbidden" ? "protected storage class" : protect === "symlink" ? "symlink is never followed" : "safety protection" }); } return { schemaVersion: 1, generatedAt: new Date().toISOString(), roots, items, bytes: items.reduce((sum, item) => sum + item.bytes, 0), candidates: items.filter((item) => item.protection === "candidate").reduce((sum, item) => sum + item.bytes, 0), protectedBytes: items.filter((item) => item.protection !== "candidate").reduce((sum, item) => sum + item.bytes, 0) }; }
export async function loadConfig(root: string): Promise<Config> { try { return JSON.parse(await readFile(join(root, ".agent-prune.json"), "utf8")) as Config; } catch { return { pins: [] }; } }
export async function saveConfig(root: string, config: Config): Promise<void> { const { writeFile } = await import("node:fs/promises"); await writeFile(join(root, ".agent-prune.json"), `${JSON.stringify(config, null, 2)}\n`, "utf8"); }
